version: 2.1

orbs:
  my-orb: https://raw.githubusercontent.com/rosieyohannan/circle-hello-world/refs/heads/master/.circleci/my-orb.yml

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Building application"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Running standard tests"

workflows:
  main:
    jobs:
      - build
      - test:
          override-with: my-orb/custom-test
          requires: 
            - build
