version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.4
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - run:
          command: go list ./... | circleci tests run --command "xargs gotestsum --junitfile junit.xml --format testname --" --split-by=timings --timings-type=name
      - store_test_results:
          path: junit.xml

workflows:
  build-and-test:
    jobs:
      - build
