version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current

    steps:
      - run:
          name: "Deploy"
          command: "exit $((RANDOM % 2))"

workflows:
  workflow:
    max_auto_reruns: 5
    jobs:
      - deploy
