version: 2.1

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>

jobs:
  daily-message:
    docker:
      - image: cimg/base:2025.09
    parameters:
      message:
        type: string
    steps:
      - print:
          message: job message

workflows:
  my-workflow:
    jobs:
      - daily-message:
          message: workflow message
