version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Building application"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Running standard tests"

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
